In [ ]:
import tensorflow as tf
import os
#initialization
x =tf.constant(4,shape=(1,1),dtype=tf.float32) # 1*1 D matrix
x =tf.constant([[1,2,3],[4,5,6]])# 2*3 matrix

x=tf.ones((3,3))
x=tf.zeros((2,3))
x=tf.eye(3) #  identity matrix
x=tf.random.normal((3,3), mean=0, stddev=1) #stddev=standard normal Distribution
x=tf.random.uniform((1,3), minval=0, maxval=1)
x =tf.range(9)
x=tf.range(start=1,limit=10,delta=2)
x=tf.cast(x,dtype=tf.float64) #tf.float(16,32,64) tf.int(8,16,32,64)
print(x)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


In [ ]:
#Mathmethical Operation
import tensorflow as tf

x=tf.constant([1,2,3,4,5])
y=tf.constant([10,12,13,14,15])

z=tf.add(x,y)
print(z)
z=tf.subtract(x,y)
print(z)
z=tf.multiply(x,y)
print(z)
z=tf.divide(x,y)
print(z)
z=tf.tensordot(x,y,axes=1)
print(z)

tf.Tensor([11 14 16 18 20], shape=(5,), dtype=int32)
tf.Tensor([ -9 -10 -10 -10 -10], shape=(5,), dtype=int32)
tf.Tensor([10 24 39 56 75], shape=(5,), dtype=int32)
tf.Tensor([0.1        0.16666667 0.23076923 0.28571429 0.33333333], shape=(5,), dtype=float64)


In [ ]:
#indexing
import tensorflow as tf
x=tf.constant([0,1,4,5,67,1,2,3,45,6])
print(x[:])
print(x[:-1])
print(x[1:-1])
print(x[1:3])

x=tf.constant([[0,1],[2,3],[6,7]])
print(x[0,:])

tf.Tensor([ 0  1  4  5 67  1  2  3 45  6], shape=(10,), dtype=int32)
tf.Tensor([ 0  1  4  5 67  1  2  3 45], shape=(9,), dtype=int32)
tf.Tensor([ 1  4  5 67  1  2  3 45], shape=(8,), dtype=int32)
tf.Tensor([1 4], shape=(2,), dtype=int32)
tf.Tensor([0 1], shape=(2,), dtype=int32)
